---
# ansible-playbook linux-setup.yml --ask-pass

- name: Package installs and elavated user setup
  hosts: debian
  gather_facts: false
  become: yes

  roles:
    - role: install_packages
      tags:
        - packages
    - role: elevated_setup
      tags:
        - e_setup
    - role: user_files
      tags:
        - files

- name: Non-root setup
  hosts: debian
  gather_facts: false
  become: no

  roles:
    - role: normal_setup
      tags:
        - n_setup
