---
# ansible-playbook linux-setup.yml --ask-pass
- name: Set up Linux machines
  hosts: ubuntu
  gather_facts: false

  tasks:
    - name: Add vim repo
      ansible.builtin.apt_repository:
        repo: ppa:jonathonf/vim
        state: present
      become: true

    - name: Install Ubuntu packages
      ansible.builtin.apt:
        pkg:
          - exa
          - zsh
          - vim=2:9.0.0749-0york0~22.04
          - tmux
        state: present
        update_cache: true
      become: true

    - name: Change shell to zsh
      user:
        name: josue
        shell: /bin/zsh
      become: yes

    - name: Install vim Airline and oh-my-zsh
      ansible.builtin.git:
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
        version: master
      loop:
        - repo: https://github.com/vim-airline/vim-airline
          dest: ~/.vim/pack/dist/start/vim-airline
        - repo: https://github.com/vim-airline/vim-airline-themes
          dest: ~/.vim/pack/dist/start/vim-airline-themes
        - repo: https://github.com/ohmyzsh/ohmyzsh.git
          dest: ~/.oh-my-zsh
        - repo: https://github.com/romkatv/powerlevel10k.git
          dest: ~/.oh-my-zsh/custom/themes/powerlevel10k

    - name: Set Git global vars
      community.general.git_config:
        name: "{{ item.name }}"
        scope: global
        value: "{{ item.value }}"
      loop:
        - name: init.defaultBranch
          value: main
        - name: user.name
          value: "Josue M"
        - name: user.email
          value: "josue_dev@fastmail.com"

    - name: Set sudoers
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode }}"
      become: true
      tags:
        - sudoers
      loop:
        # SUDO w/o password
        - src: files/sodoers
          dest: /etc/sudoers.d/josue-by-ansible
          mode: "0440"

    - name: Create directories
      ansible.builtin.file:
        path: ~/.vim/colors
        state: directory
        mode: "0755"

    - name: Copy user files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode }}"
      tags:
        - user-files
      loop:
        # SSH stuff
        - src: files/authorized_keys
          dest: ~/.ssh/authorized_keys
          mode: "0700"
        - src: files/ssh_config
          dest: ~/.ssh/config
          mode: "0700"
        # aliases and helpers
        - src: files/aliases
          dest: ~/.aliases
          mode: "0664"
        - src: files/helpers
          dest: ~/.helpers
          mode: "0664"
        # tmux
        - src: files/tmux.conf
          dest: ~/.tmux.conf
          mode: "0664"
        # vim
        - src: files/.vimrc
          dest: ~/.vimrc
          mode: "0664"
        - src: files/atom-dark-256.vim
          dest: ~/.vim/colors/atom-dark-256.vim
          mode: "0664"
        # zsh
        - src: files/.zshrc
          dest: ~/.zshrc
          mode: "0664"
        - src: files/.p10k.zsh
          dest: ~/.p10k.zsh
          mode: "0664"
